/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/**
* @file pex_connected.h
* @author Ivano Cerrato<ivano.cerrato (at) polito.it>
*
* @brief PEX abstraction and API.
*/

#define PEX_MAX_LEN_NAME 32

/**
* @brief List of PEXes name (snapshots)
*/
typedef struct __pex_port_name{
	char name[PEX_MAX_LEN_NAME]; 
}__pex_port_name_t;

typedef struct pex_port_name_list
{
	//Number of PEXes in the PEX list
	unsigned int num_of_pex;
	
	//Names
	__pex_port_name_t* names;
}pex_port_name_list_t; 


/* 
* Functions
*/


//C++ extern C
ROFL_BEGIN_DECLS

/**
* @brief Destroys a PEX name list, previously generated by calling fwd_module_get_all_port_names()
*/
void pex_port_name_list_destroy(pex_port_name_list_t* list);

//C++ extern C
ROFL_END_DECLS
