#!/bin/sh

#SRCDIR=$1
#shift

cat <<EOF
/**
 * automatically generated by $0 $*
 * do not edit
 */
#ifndef PLATFORM_LOCK_H_
#define PLATFORM_LOCK_H_

#include "$1/lock_types.h"

#endif /* PLATFORM_LOCK_H_ */
EOF

