#!/bin/sh

SRCDIR=$1
shift

cat <<-EOF
/**
 * automatically generated by $0 $*
 * do not edit
 */

#ifndef MATCHING_ALGORITHMS_AVAILABLE_PP_H_
#define MATCHING_ALGORITHMS_AVAILABLE_PP_H_

#error "HEEEEY"
EOF

for ALG in "$@"; do
	file_name=$SRCDIR"/"$ALG"/of1x_"$ALG"_ma_pp.h"
	if test -e "$file_name";then
		echo "#include <rofl/datapath/pipeline/openflow/openflow1x/matching_algorithms/"$ALG"/of1x_"$ALG"_ma_pp.h>"
	fi
done

cat <<-EOF

#endif /* MATCHING_ALGORITHMS_AVAILABLE_PP_H_ */

EOF
