#!/bin/sh

SRCDIR=$1
shift

cat <<EOF
/**
 * automatically generated by $0 $*
 * do not edit
 */

#include "matching_algorithms.h"
#include "available_ma.h"

EOF

# write the includes
for ALG in "$@"; do
	if test -d $SRCDIR/$ALG; then
		echo "#include \"${ALG}/of1x_${ALG}_ma.h\""
	else
		echo "#include <rofl/datapath/pipeline/openflow/openflow1x/pipeline/matching_algorithms/${ALG}/of1x_${ALG}_ma.h>"
	fi
done

# print extern for matching algorithms 
for alg in "$@"; do
echo "extern of1x_matching_algorithms_functions_t of1x_matching_algorithm_${alg}_maf;"
done 

cat <<EOF
/* Main matching algorithm array */
of1x_matching_algorithms_functions_t of1x_matching_algorithms[of1x_matching_algorithm_count];


/* Filling */
void __of1x_generate_matching_algorithm_list(){
EOF

counter=0
for alg in "$@"; do
echo "of1x_matching_algorithms[${counter}] = of1x_matching_algorithm_${alg}_maf;"
counter=`expr $counter + 1`
done 


cat <<EOF
}
EOF


