#!/bin/sh

cat <<-EOF
/**
 * automatically generated by $0 $*
 * do not edit
 */

#ifndef MATCHING_ALGORITHMS_AVAILABLE_H_
#define MATCHING_ALGORITHMS_AVAILABLE_H_

enum of1x_matching_algorithm_available{
EOF

for ALG in "$@"; do
	last_ma="of1x_"$ALG"_matching_algorithm"
	echo $last_ma","
done

cat <<-EOF
};

EOF
echo "//Define maximum out of the enum"
echo "#define of1x_matching_algorithm_count ("$last_ma" + 1)"
cat <<-EOF

#define OF1X_MATCHING_ALGORITHM_NAMES \\
{ \\
EOF

for ALG in "$@"; do
	echo "	\"$ALG\", \\"
done

cat <<-EOF
}

#endif /* MATCHING_ALGORITHMS_AVAILABLE_H_ */

EOF
