#!/bin/sh

SRCDIR=$1
shift

cat <<EOF
/**
 * automatically generated by $0 $*
 * do not edit
 */

#include "matching_algorithms.h"
#include "matching_algorithms_available.h"

EOF

# write the includes
for ALG in "$@"; do
	if test -d $SRCDIR/$ALG; then
		echo "#include \"${ALG}/of12_${ALG}_match.h\""
	else
		echo "#include <rofl/pipeline/openflow/openflow12/pipeline/matching_algorithms/${ALG}/of12_${ALG}_match.h>"
	fi
done

# print extern for matching algorithms 
for alg in "$@"; do
echo "extern of12_matching_algorithms_functions_t of12_matching_algorithm_${alg}_maf;"
done 

cat <<EOF
/* Main matching algorithm array */
of12_matching_algorithms_functions_t of12_matching_algorithms[of12_matching_algorithm_count];


/* Filling */
void __of12_generate_matching_algorithm_list(){
EOF

counter=0
for alg in "$@"; do
echo "of12_matching_algorithms[${counter}] = of12_matching_algorithm_${alg}_maf;"
counter=`expr $counter + 1`
done 


cat <<EOF
}
EOF


